/**/ekf_local:
  ros__parameters:
    frequency: 15.0
    two_d_mode: false
    publish_tf: true

    map_frame: "icp_map"
    odom_frame: "ekf_odom"
    base_link_frame: "base_link"
    world_frame: "ekf_odom"

    # IMU (Angular Velocity & Linear Accel)
    imu0: "/dvl/imu"
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false,  false,  false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
    # imu0_pose_rejection_threshold: 0.8      
    # imu0_twist_rejection_threshold: 0.8


    # DVL (Linear Velocity)
    twist0: "/dvl/velocity"
    twist0_config: [false, false, false,
                    false, false, false,
                    true,  true,  false,   # X, Y, Z velocities
                    false, false, false,
                    false, false, false]
    twist0_rejection_threshold: 2.0


/**/ekf_global:
  ros__parameters:
    frequency: 15.0
    two_d_mode: false
    publish_tf: true
    history_length: 1.0
    smooth_lagged_data: true

    map_frame: "icp_map"
    odom_frame: "ekf_odom"
    base_link_frame: "base_link"
    world_frame: "icp_map"

    imu0: "/dvl/imu"
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false,  false,  false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
    
    # imu1: "/dvl/ahrs_imu"
    # imu1_config: [false, false, false,
    #               true, true, true,
    #               false, false, false,
    #               false,  false,  false,
    #               false,  false,  false]
    # imu1_differential: false
    # imu1_relative: false
    # imu1_remove_gravitational_acceleration: true

    # imu1_remove_gravitational_acceleration: true

    twist0: "/dvl/velocity"
    twist0_config: [false, false, false,
                    false, false, false,
                    true,  true,  false,
                    false, false, false,
                    false, false, false]
    twist0_rejection_threshold: 2.0
    pose0: "/depth_odom"
    pose0_config: [false, false, true,    
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    # odom0: "odometry/gps"         
    # odom0_config: [true,  true,  false,
    #                false, false, true,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]
    # odom0_differential: false
    # odom0_relative:     false
    # odom0_rejection_threshold: 2.0

    # odom0: /vgicp_odom
    # odom0_config: [true,  true,  false,
    #                false,  false,  true,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]
    
    # odom0_differential: true
    # PLUS THE ABSOLUTE DEPTH


/**/ekf_gps:
  ros__parameters:
    frequency: 10.0
    two_d_mode: true
    publish_tf: false

    map_frame: "icp_map"
    odom_frame: "gps_odom"
    base_link_frame: "base_link"
    world_frame: "icp_map"

    odom0: "odometry/gps_ned"         
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative:     false
    odom0_rejection_threshold: 2.0

    imu0: "/dvl/imu"
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false,  false,  false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true


    twist0: "/dvl/velocity"
    twist0_config: [false, false, false,
                    false, false, false,
                    true,  true,  false,
                    false, false, false,
                    false, false, false]
    twist0_rejection_threshold: 2.0

/navsat_transform_node:
  ros__parameters:
    use_sim_time: true
    frequency: 10.0
    delay: 0.0
    magnetic_declination_radians: 0.13 # Change this based on your city (e.g., 0.21 for NYC)
    yaw_offset: 1.57      # IMU reads 0 at North? If not, adjust (1.57 is 90 deg)
    zero_altitude: true              # Use if you only care about XY movement
    publish_filtered_gps: true       # Useful for debugging on a map
    broadcast_cartesian_transform: false
    use_odometry_yaw: true           # use EKF heading instead of IMU orientation
    wait_for_datum: false


# smooth_lagged_data: true
# history_length: 1.0